### PR TITLE
Update Translation Assistant submodule

### PR DESCRIPTION
**Pull request by danielhollas**
PR accompanying the PR on translation-assistant repo https://github.com/Khan/translation-assistant/pull/51. The submodule here doesn't yet point to the correct commit. I will update this once the TA PR gets merged.

### CODE REVIEW

**Comment by justinmayhew** [comment]
Hi @danielhollas, Khan/translation-assistant#51 has been merged. Could you update the submodule? Let me know if you're busy and I'll take care of it. Thanks again!

**Comment by danielhollas** [comment]
@justinmayhew thanks for taking this on! I've updated the submodule. LMK in case you run into issues publishing this plugin to Chrome store. When I was transferring this repo to Khan I've tried to document the process as much as possible in `DEV.md`, but this is the first time that a new version of the plugin will be published by Khan.

Note that the Firefox version of this plugin is still maintained by me. We didn't transfer it because the number of users on Firefox is minimal. I will publish the Firefox version once you confirm that the Chrome version was published. Thanks!

**Review by justinmayhew — APPROVED** [review]
Awesome, thanks! I'll be sure to let you know when the Chrome version is published. 🙌

**Comment by justinmayhew** [comment]
@danielhollas the new Chrome version (3.5.0) is published.

**Comment by danielhollas** [comment]
Excellent, thanks! Has the new Translation Assistant been deployed to webapp?

**Comment by justinmayhew** [comment]
Yeah, it was deployed yesterday.

**Pull request merged**
